### ISSUE TITLE
Remove ignore of valgrind test results in CI

### ISSUE THREAD

**Issue by alexander-penev** [compiler-research/CppInterOp#174]
https://github.com/compiler-research/CppInterOp/blob/2d933477e93f36e1029a2996358b7daa93d8aa0f/.github/workflows/ci.yml#L393

Remove "|| true" when fix memory issues in LLVM/Clang 17.

**Comment by mcbarton** [comment]
Closing as this was done at some point, but this issue wasn't closed.
