### ISSUE TITLE
Add WASM CI Support

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/CppInterOp#183]
The wasm support should be compatible to what's already done for the [xeus-cpp](https://github.com/compiler-research/xeus-cpp) project where I would like to eventually adopt CppInterOp.

**Comment by mcbarton** [comment]
@vgvassilev I'm just waiting for the Windows CppInterOp build to pass in https://github.com/compiler-research/CppInterOp/pull/181 and be merged, and then I plan add on a Windows cppyy build to the PR. I'll try to address this WASM support in that PR.

**Comment by vgvassilev** [comment]
Ok, awesome!

**Comment by vgvassilev** [comment]
Looks like the windows work is almost done. Maybe a good time to start the WASM work.
