### ISSUE TITLE
Investigate the valgrind invalid memory accesses in released llvm 17.

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/CppInterOp#184]
LLVM 17 seems broken. It has valgrind issues discovered by CppInterOp: https://github.com/compiler-research/CppInterOp/actions/runs/7561682890/job/20590508932#step:26:11915

**Comment by mcbarton** [comment]
This issue feels like a copy of issue https://github.com/compiler-research/CppInterOp/issues/174 , or at least very related.

**Comment by vgvassilev** [comment]
Yes, that's right, let's close it as duplicate.
