### ISSUE TITLE
wasm nightly builds fail

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/CppInterOp#199]
Our current master seems to fail during wasm builds. @mcbarton, do you know if that's expected and if we can fix it?

**Comment by mcbarton** [comment]
@vgvassilev The last 2 nightly builds have all passed for the wasm builds, since the cache was cleared. Can you point to me it is failing? The reason it failed when it merged was due to it using the incompatible llvm builds.

**Comment by vgvassilev** [comment]
Ha, you are right. Apparently when we merge something on the front page of the code tab github records the run (from 3 days ago) and does not update it. Sorry for the noise. Now I can look how to release CppInterOp!
