### ISSUE TITLE
Implement GetArrayDimensions

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/CppInterOp#21]
https://github.com/compiler-research/InterOp/blob/a16dedef4d8fa7d5833b179954c073726016d4bf/unittests/InterOp/VariableReflectionTest.cpp#L228-L249

**Comment by Smit1603** [comment]
- I believe this can be achieved using GetDimension module??
- Do we have to implement this??

**Comment by sudo-panda** [comment]
Yeah this can be closed
