### ISSUE TITLE
Doxygen documentation regeneration

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/CppInterOp#243]
Looks like our documentation does not pick up the doxygen style comments: https://cppinterop.readthedocs.io/en/latest/build/html/index.html

I am not sure if that's a feature or we are just not regenerating the documentation.

**Comment by mcbarton** [comment]
I think this could be added as part of the nightly builds on the ci. We could add something that builds the documentation, and pushes the changes to this webpage.

**Comment by vgvassilev** [comment]
> I think this could be added as part of the nightly builds on the ci. We could add something that builds the documentation, and pushes the changes to this webpage.

I believe that was part of the readthedocs website infrastructure. I just was not sure if the problem was the way we build our documentation or if we are not triggering new builds. 

In #246 we landed a new interface and it seems to be showing there which means we regenerate the documentation but we do not take the comments...

**Comment by vgvassilev** [comment]
We seem to have hit some bug because all interface documentation is attached to the __attribute__() : https://cppinterop.readthedocs.io/en/latest/build/html/namespaceCpp.html#a3ef57f5fc1b6bf7e59bc40e340fd2be6

**Comment by mcbarton** [comment]
This was fixed by https://github.com/compiler-research/CppInterOp/pull/381
