### ISSUE TITLE
Extra space in function signature.

### ISSUE THREAD

**Issue by sudo-panda** [compiler-research/CppInterOp#84]
https://github.com/compiler-research/InterOp/blob/5e0884484c579b0b79bec1532e8296586ea2cce5/lib/Interpreter/InterOp.cpp#LL988C32-L988C63

There is a large gap in the function signature.

**Comment by vgvassilev** [comment]
Does that occur elsewhere?

**Comment by Smit1603** [comment]
@vgvassilev This issue can be closed

**Comment by vgvassilev** [comment]
Indeed.
