### ISSUE TITLE
Need Help with Missing Definitions - InterOp Doxygen Documentation Comments

### ISSUE THREAD

**Issue by QuillPusher** [compiler-research/CppInterOp#86]
@vgvassilev  Adding separate issue alongside PR #85 to add more context.

As discussed during the Weekly Documentation Meeting, please help add missing comments for Doxygen documentation where you can, specifically for 

1. Function Definitions (mostly covered in PR 85)
2. Parameters  ( \param )
3. Return Values ( \return )

**Comment by vgvassilev** [comment]
@QuillPusher is that issue resolved?

**Comment by QuillPusher** [comment]
No, but this is an optional issue. 

You (@vgvassilev) mentioned during our docs meeting that you could also help add some definitions (code comments) for the CppInterOp Documentation. 

I took all the info from Baidyanath's session and added the comments (PR #85 ), but there's still room for improvement (e.g., better  \param  and \return values).

On the other hand, you've already reviewed my comments/definitions in PR #85 , so if no big area seemed lacking then this issue can be closed (and we can aim for improvement in the next documentation iteration).
